### ISSUE TITLE
function_exists and postgresql 9.1

### ISSUE THREAD

**Issue by vladget** [mixerp/plpgunit#6]
I dont have a lot experience with portgresql 9.3 version... but at 9.1 it looks like bug:

"        message := 'The function % does not exist.', $1;" 
or this missed format() function or use classic concatenation by "||"
here is my patch, just in case:

@@ -359,7 +359,7 @@ BEGIN
         ON      pronamespace = n.oid
         WHERE replace(nspname || '.' || proname || '(' || oidvectortypes(proargtypes) || ')', ' ' , '')::text=$1
     ) THEN
-        message := 'The function % does not exist.', $1;
+        message := 'The function ' || $1 || ' does not exist.';
         PERFORM assert.fail(message);
 
         result := false;

**Comment by mixerp** [comment]
Absolutely. It looks totally wrong to me too. I will fix ASAP. Thanks for pointing out. :+1:

**Comment by mixerp** [comment]
Solved.
