### ISSUE TITLE
assert.is_greater_than at 9.1 does not work.... 

### ISSUE THREAD

**Issue by vladget** [mixerp/plpgunit#7]
assert.is_greater_than does not work at 9.1....

**Comment by mixerp** [comment]
Hi, could you please let me know what errors you get?

**Comment by vladget** [comment]
: function assert.is_greater_then(double precision, double precision) does not exist

**Comment by mixerp** [comment]
Hi,

I think you misspelled it. :)

**Comment by vladget** [comment]
No. I've double checked at pg_proc

среда, 11 марта 2015 г. пользователь MixERP написал:

> Hi,
>
> I think you misspelled it. :)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mixerp/plpgunit/issues/7#issuecomment-78380811>.
>


-- 
Yours sincerely,
Vladimir Getmanshchuk

**Comment by mixerp** [comment]
There is no such function called ```assert.is_greater_then``` in plpgunit. It should be ```assert.is_greater_than```

**Comment by vladget** [comment]
:) mess... I'm so sorry about that.... Thank you!

**Comment by mixerp** [comment]
You're welcome. vlad.
