### ISSUE TITLE
assert.is_equal does poor comparison when a parameter is null

### ISSUE THREAD

**Issue by filipposantovito** [mixerp/plpgunit#8]
assert.is_equal(NULL, 0) should return false 

    IF($1 = $2) THEN
should be replaced with: 

    IF $1 is not distinct from $2 THEN

and the function can't be declared STRICT

[is not distinct from](http://www.postgresql.org/docs/9.3/static/functions-comparison.html) documentation
[strict](http://www.postgresql.org/docs/9.3/static/sql-createfunction.html) documentation

maybe there are other functions to be checked for the same bug.

**Comment by filipposantovito** [comment]
you also need to change the error message with:

    message := E'ASSERT IS_EQUAL FAILED.\n\nHave -> ' || coalesce($1::text, 'NULL') || E'\nWant -> ' || coalesce($2::text, 'NULL') || E'\n';

**Comment by mixerp** [comment]
Okay. Makes a perfect sense. Let me see if this applies to other functions as well. Thank you.
